<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SitemapController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| The React app uses BrowserRouter with real URL paths (no #/).
| Laravel serves index.html for every non-API, non-asset request so
| React Router can handle client-side navigation on page load/refresh.
|
*/

// ── Sitemap & Robots — must be before the SPA catch-all ─────────────────────
Route::get('/sitemap.xml', [SitemapController::class, 'index']);
Route::get('/robots.txt',  [SitemapController::class, 'robots']);

// ── Dynamic Favicon — serves the admin-uploaded favicon from DB ───────────────
// .htaccess routes favicon.ico through Laravel (bypasses static file).
// Uses 302 + no-store so browsers and Google never cache the redirect —
// every request re-checks the DB for the latest favicon.
Route::get('/favicon.ico', function () {
    $faviconUrl = null;
    try {
        $setting = \App\Models\Setting::where('key', 'faviconUrl')->first();
        if ($setting) {
            $decoded    = json_decode($setting->value, true);
            $faviconUrl = is_string($decoded) ? $decoded : $setting->value;
        }
    } catch (\Throwable $e) { /* DB not ready — fall through */ }

    // External URL → 302 (temporary) redirect with no-store so it is never cached
    // 301 was causing browsers and Google to permanently cache the old URL.
    if ($faviconUrl && str_starts_with($faviconUrl, 'http')) {
        return redirect()->away($faviconUrl, 302)
            ->header('Cache-Control', 'no-store, no-cache, must-revalidate')
            ->header('Pragma', 'no-cache');
    }

    // Base64 data URI → decode and serve the raw image bytes inline
    if ($faviconUrl && str_starts_with($faviconUrl, 'data:')) {
        if (preg_match('/^data:([^;]+);base64,(.+)$/', $faviconUrl, $m)) {
            return response(base64_decode($m[2]), 200)
                ->header('Content-Type',  $m[1])
                ->header('Cache-Control', 'no-store, no-cache, must-revalidate')
                ->header('Pragma', 'no-cache')
                ->header('X-Favicon-Source', 'dashboard');
        }
    }

    // Fall back to static file in public/
    $static = public_path('favicon.ico');
    if (file_exists($static)) {
        return response()->file($static, [
            'Content-Type'  => 'image/x-icon',
            'Cache-Control' => 'no-store, no-cache, must-revalidate',
        ]);
    }

    return response('Not found', 404);
});

// ── SPA catch-all — serves index.html for ALL public routes ──────────────────
// BrowserRouter requires every path to return index.html so React Router
// can boot and render the correct page client-side.
Route::get('/{any?}', function () {
    // ── Guard: never intercept real static files ─────────────────────────────
    // If the URL maps to a real file in /public (e.g. /assets/react-core-xxx.js),
    // let Apache/Nginx serve it directly. This route should only handle SPA paths.
    $requestPath = ltrim(request()->getPathInfo(), '/');
    $filePath    = public_path($requestPath);
    if ($requestPath !== '' && file_exists($filePath) && !is_dir($filePath)) {
        return response()->file($filePath);
    }

    $indexPath = public_path('index.html');

    if (!file_exists($indexPath)) {
        return response(
            '<h2 style="font-family:sans-serif;padding:2rem">
              Frontend not built yet.<br>
              Run <code>npm install && npm run build</code> from the project root.
             </h2>',
            200
        )->header('Content-Type', 'text/html');
    }

    // ── ETag / conditional GET ───────────────────────────────────────────────
    // Generate an ETag from the file modification time + size.
    // On repeat visits the browser sends If-None-Match; if unchanged we return
    // 304 with zero body, cutting TTFB payload to ~200 bytes.
    $mtime = filemtime($indexPath);
    $size  = filesize($indexPath);
    $etag  = '"' . dechex($mtime) . '-' . dechex($size) . '"';
    $lastModified = gmdate('D, d M Y H:i:s', $mtime) . ' GMT';

    $ifNoneMatch   = request()->header('If-None-Match');
    $ifModifiedSince = request()->header('If-Modified-Since');

    $notModified = ($ifNoneMatch === $etag)
        || (!$ifNoneMatch && $ifModifiedSince && strtotime($ifModifiedSince) >= $mtime);

    if ($notModified) {
        return response('', 304)
            ->header('ETag',          $etag)
            ->header('Last-Modified', $lastModified)
            ->header('Cache-Control', 'public, max-age=0, must-revalidate')
            ->header('Vary',          'Accept-Encoding');
    }

    // ── Read + optionally compress inline ──────────────────────────────────
    // Apache mod_deflate only compresses content generated by PHP output.
    // response()->file() bypasses PHP output — compression never fires.
    // We apply gzip/zstd here ourselves so the HTML document is always
    // served compressed, reducing the first-paint payload.
    $content  = file_get_contents($indexPath);
    $headers  = [
        'Content-Type'  => 'text/html; charset=UTF-8',
        'ETag'          => $etag,
        'Last-Modified' => $lastModified,
        // no-cache means "revalidate every time" — the ETag check above
        // makes repeat visits a 304 with zero body cost.
        'Cache-Control' => 'public, max-age=0, must-revalidate',
        'Vary'          => 'Accept-Encoding',
    ];

    $acceptEncoding = request()->header('Accept-Encoding', '');

    // Brotli — best compression, ~15 % smaller than gzip
    if (function_exists('brotli_compress') && str_contains($acceptEncoding, 'br')) {
        $compressed = brotli_compress($content, 4);
        if ($compressed !== false) {
            $headers['Content-Encoding'] = 'br';
            return response($compressed, 200, $headers);
        }
    }

    // Gzip — universal fallback
    if (str_contains($acceptEncoding, 'gzip')) {
        $compressed = gzencode($content, 6);
        if ($compressed !== false) {
            $headers['Content-Encoding'] = 'gzip';
            return response($compressed, 200, $headers);
        }
    }

    // No compression support — serve plain
    return response($content, 200, $headers);
})->where('any', '.*');